#!/usr/bin/env python3
"""
log_transaction.py — Append a one-off transaction to data/transactions.json.

Use for any unit-changing event you want to log immediately:
  - lump-sum purchase
  - manual redemption
  - dividend reinvestment (treated as a purchase using payout NAV)
  - one-off switch (run twice: switch-out + switch-in, link via --link-to)

Recurring SIPs/STPs do NOT use this — they are generated by recurring_runner.py
from data/recurring.json. Use this only for ad-hoc transactions.

Usage examples:

    # Lump-sum purchase, NAV auto-fetched from market.db
    python log_transaction.py purchase \\
        --date 2026-05-10 --scheme-code 122639 --amount 5000 \\
        --sub-portfolio user

    # Override NAV (e.g., when the real NAV differs from the day's close)
    python log_transaction.py purchase \\
        --date 2026-05-10 --scheme-code 122639 --amount 5000 \\
        --sub-portfolio user --nav 78.4521

    # Redemption — must specify --tax-category for FIFO + gain classification
    python log_transaction.py redemption \\
        --date 2026-05-10 --scheme-code 108768 --units 875.62 \\
        --sub-portfolio father --tax-category specified-mf

    # Switch (two calls, linked)
    python log_transaction.py switch-out \\
        --date 2026-05-10 --scheme-code 100596 --units 100 \\
        --sub-portfolio father --tax-category equity \\
        --notes "Switching Bandhan L&M Reg → Direct"

Exit codes: 0 success, 1 user error, 2 NAV-not-available
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Allow running as module or script.
SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from lib.db import get_conn  # noqa: E402
from lib.transactions import (  # noqa: E402
    VALID_TAX_CATEGORIES,
    VALID_SUB_PORTFOLIOS,
    load_transactions,
    save_transactions,
    make_purchase,
    make_redemption,
    validate_transaction,
    get_nav_on_date,
    nearest_business_day_nav,
)


def _scheme_name(conn, scheme_code: int) -> str:
    row = conn.execute(
        "SELECT scheme_name FROM schemes WHERE scheme_code = ?", (scheme_code,)
    ).fetchone()
    return row[0] if row else f"<unknown scheme {scheme_code}>"


def _resolve_nav(conn, scheme_code: int, date_str: str, override: float | None) -> tuple[float, str]:
    """
    Return (nav, source_note). Prefers override if given. Else exact-date.
    Else nearest-forward business day. Raises SystemExit(2) if nothing within 7 days.
    """
    if override is not None:
        return (override, f"user-override")
    exact = get_nav_on_date(scheme_code, date_str, conn)
    if exact is not None:
        return (exact, f"market.db exact {date_str}")
    fwd = nearest_business_day_nav(scheme_code, date_str, conn, direction="forward", max_days=7)
    if fwd:
        actual_date, nav = fwd
        return (nav, f"market.db forward-fallback {actual_date} (target {date_str})")
    bwd = nearest_business_day_nav(scheme_code, date_str, conn, direction="backward", max_days=7)
    if bwd:
        actual_date, nav = bwd
        return (nav, f"market.db backward-fallback {actual_date} (target {date_str})")
    print(
        f"ERROR: No NAV in market.db for scheme {scheme_code} within ±7 days of {date_str}.\n"
        f"Run: python scripts/fetch_nav_history.py --scheme-code {scheme_code} --from-date {date_str}",
        file=sys.stderr,
    )
    raise SystemExit(2)


def cmd_purchase(args: argparse.Namespace, type_: str) -> int:
    txns = load_transactions()
    with get_conn() as conn:
        scheme_name = args.scheme_name or _scheme_name(conn, args.scheme_code)
        nav, nav_source = _resolve_nav(conn, args.scheme_code, args.date, args.nav)

    txn = make_purchase(
        date_str=args.date,
        scheme_code=args.scheme_code,
        scheme_name=scheme_name,
        amount_inr=args.amount,
        nav=nav,
        sub_portfolio=args.sub_portfolio,
        source=args.source,
        txns=txns,
        sip_id=args.sip_id,
        stp_id=args.stp_id,
        linked_txn_id=args.link_to,
        exit_load_inr=args.exit_load,
        notes=(args.notes or "") + (f" [nav: {nav_source}]" if nav_source != "user-override" else ""),
        type_=type_,
    )
    errs = validate_transaction(txn)
    if errs:
        print(f"VALIDATION FAILED:\n  - " + "\n  - ".join(errs), file=sys.stderr)
        return 1

    txns.append(txn)
    save_transactions(txns)
    print(f"Appended: {txn['txn_id']}")
    print(f"  scheme:        {scheme_name} ({args.scheme_code})")
    print(f"  amount:        ₹{args.amount:,.2f}")
    print(f"  nav:           ₹{nav:.4f}  [{nav_source}]")
    print(f"  units:         {txn['units']}")
    print(f"  sub-portfolio: {args.sub_portfolio}")
    return 0


def cmd_redemption(args: argparse.Namespace, type_: str) -> int:
    txns = load_transactions()
    with get_conn() as conn:
        scheme_name = args.scheme_name or _scheme_name(conn, args.scheme_code)
        nav, nav_source = _resolve_nav(conn, args.scheme_code, args.date, args.nav)

    try:
        txn = make_redemption(
            date_str=args.date,
            scheme_code=args.scheme_code,
            scheme_name=scheme_name,
            units_to_sell=args.units,
            nav=nav,
            sub_portfolio=args.sub_portfolio,
            source=args.source,
            txns=txns,
            tax_category=args.tax_category,
            stp_id=args.stp_id,
            linked_txn_id=args.link_to,
            exit_load_inr=args.exit_load,
            notes=(args.notes or "") + (f" [nav: {nav_source}]" if nav_source != "user-override" else ""),
            type_=type_,
        )
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    errs = validate_transaction(txn)
    if errs:
        print(f"VALIDATION FAILED:\n  - " + "\n  - ".join(errs), file=sys.stderr)
        return 1

    txns.append(txn)
    save_transactions(txns)
    print(f"Appended: {txn['txn_id']}")
    print(f"  scheme:           {scheme_name} ({args.scheme_code})")
    print(f"  units sold:       {args.units}")
    print(f"  nav:              ₹{nav:.4f}  [{nav_source}]")
    print(f"  proceeds:         ₹{abs(txn['amount_inr']):,.2f}  (after exit-load ₹{args.exit_load:,.2f})")
    print(f"  cost basis used:  ₹{txn['cost_basis_consumed_inr']:,.2f}")
    print(f"  realised gain:    ₹{txn['realised_gain_inr']:,.2f}")
    print(f"  classification:   {txn['gain_classification']}")
    print(f"  FIFO lots used:   {len(txn['fifo_lots_consumed'])}")
    for lot in txn["fifo_lots_consumed"]:
        print(f"    - {lot['units']} units from {lot['source_txn_id']} ({lot['purchase_date']})")
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    def add_common(sp):
        sp.add_argument("--date", required=True, help="ISO date YYYY-MM-DD")
        sp.add_argument("--scheme-code", required=True, type=int)
        sp.add_argument("--scheme-name", default=None,
                        help="Override; default looked up from market.db")
        sp.add_argument("--sub-portfolio", required=True, choices=sorted(VALID_SUB_PORTFOLIOS))
        sp.add_argument("--nav", type=float, default=None,
                        help="Override NAV; default from market.db")
        sp.add_argument("--exit-load", type=float, default=0.0)
        sp.add_argument("--source", default="user-dictated",
                        help="Provenance tag (default user-dictated)")
        sp.add_argument("--sip-id", default=None)
        sp.add_argument("--stp-id", default=None)
        sp.add_argument("--link-to", default=None,
                        help="txn_id this transaction is linked to (switch pair)")
        sp.add_argument("--notes", default="")

    p_buy = sub.add_parser("purchase", help="Lump-sum purchase or dividend reinvestment")
    add_common(p_buy)
    p_buy.add_argument("--amount", required=True, type=float, help="₹ invested")

    p_swin = sub.add_parser("switch-in", help="Buy leg of a switch (use with switch-out)")
    add_common(p_swin)
    p_swin.add_argument("--amount", required=True, type=float)

    p_red = sub.add_parser("redemption", help="Sell units; FIFO computes cost basis + gain")
    add_common(p_red)
    p_red.add_argument("--units", required=True, type=float, help="units sold")
    p_red.add_argument("--tax-category", required=True, choices=sorted(VALID_TAX_CATEGORIES))

    p_swout = sub.add_parser("switch-out", help="Sell leg of a switch")
    add_common(p_swout)
    p_swout.add_argument("--units", required=True, type=float)
    p_swout.add_argument("--tax-category", required=True, choices=sorted(VALID_TAX_CATEGORIES))

    return p


def main() -> int:
    args = build_parser().parse_args()
    if args.cmd == "purchase":
        return cmd_purchase(args, "purchase")
    if args.cmd == "switch-in":
        return cmd_purchase(args, "switch-in")
    if args.cmd == "redemption":
        return cmd_redemption(args, "redemption")
    if args.cmd == "switch-out":
        return cmd_redemption(args, "switch-out")
    return 1


if __name__ == "__main__":
    sys.exit(main())
